/* eslint-disable */
import React, { useState, useMemo } from 'react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Copy, Check, Download } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import MonacoEditor from '@monaco-editor/react';

interface CodePanelProps {
  language: 'javascript' | 'python';
  nodes: any[];
}

const codeTemplates = {
  javascript: {
    empty: `// Welcome to Automate2Code! ✨
// Add nodes to your canvas to see generated code here

async function workflow() {
  // Your automation workflow will appear here
  console.log('Ready to build something amazing!');
}

export default workflow;`,
    
    http: `// Generated by Automate2Code ✨
import fetch from 'node-fetch';

async function workflow() {
  try {
    // HTTP Request Node
    const response = await fetch('https://api.example.com/data', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer YOUR_TOKEN'
      }
    });
    
    const data = await response.json();
    console.log('Fetched data:', data);
    
    return data;
  } catch (error) {
    console.error('Request failed:', error);
    throw error;
  }
}

export default workflow;`,

    transform: `// Generated by Automate2Code ✨
import fetch from 'node-fetch';

async function workflow() {
  try {
    // HTTP Request
    const response = await fetch('https://api.example.com/data');
    const rawData = await response.json();
    
    // Transform Data Node
    const transformedData = rawData.map(item => ({
      id: item.id,
      title: item.name?.toUpperCase() || 'Untitled',
      category: item.type || 'general',
      processed: true,
      timestamp: new Date().toISOString()
    }));
    
    console.log('Transformed data:', transformedData);
    return transformedData;
  } catch (error) {
    console.error('Workflow failed:', error);
    throw error;
  }
}

export default workflow;`,

    conditional: `// Generated by Automate2Code ✨
import fetch from 'node-fetch';

async function workflow() {
  try {
    // HTTP Request
    const response = await fetch('https://api.example.com/data');
    const data = await response.json();
    
    // Conditional Logic Node
    if (data.length > 10) {
      console.log(\`Processing large dataset: \${data.length} items\`);
      
      // Handle large dataset
      const batched = [];
      for (let i = 0; i < data.length; i += 10) {
        batched.push(data.slice(i, i + 10));
      }
      return batched;
      
    } else {
      console.log(\`Processing small dataset: \${data.length} items\`);
      
      // Handle small dataset
      return data.map(item => ({ ...item, processed: true }));
    }
  } catch (error) {
    console.error('Workflow failed:', error);
    throw error;
  }
}

export default workflow;`,

    output: `// Generated by Automate2Code ✨
import fetch from 'node-fetch';
import fs from 'fs/promises';

async function workflow() {
  try {
    // HTTP Request
    const response = await fetch('https://api.example.com/data');
    const data = await response.json();
    
    // Process data
    const processed = data.map(item => ({
      ...item,
      processed: true,
      timestamp: new Date().toISOString()
    }));
    
    // Output Node - Export Results
    await fs.writeFile(
      'output.json', 
      JSON.stringify(processed, null, 2)
    );
    
    console.log(\`Successfully exported \${processed.length} items to output.json\`);
    
    // Also log to console
    console.table(processed.slice(0, 5)); // Preview first 5 items
    
    return {
      success: true,
      itemsProcessed: processed.length,
      outputFile: 'output.json'
    };
  } catch (error) {
    console.error('Workflow failed:', error);
    throw error;
  }
}

export default workflow;`
  },
  
  python: {
    empty: `# Welcome to Automate2Code! ✨
# Add nodes to your canvas to see generated code here

def workflow():
    """Your automation workflow will appear here"""
    print("Ready to build something amazing!")
    return True

if __name__ == "__main__":
    workflow()`,
    
    http: `# Generated by Automate2Code ✨
import requests
import json
from typing import Dict, Any

def workflow() -> Dict[str, Any]:
    """HTTP Request automation workflow"""
    try:
        # HTTP Request Node
        response = requests.get(
            'https://api.example.com/data',
            headers={
                'Content-Type': 'application/json',
                'Authorization': 'Bearer YOUR_TOKEN'
            },
            timeout=30
        )
        
        response.raise_for_status()
        data = response.json()
        
        print(f"Fetched data: {data}")
        return data
        
    except requests.RequestException as e:
        print(f"Request failed: {e}")
        raise

if __name__ == "__main__":
    result = workflow()
    print(f"Workflow completed: {result}")`,

    transform: `# Generated by Automate2Code ✨
import requests
import json
from typing import Dict, List, Any
from datetime import datetime

def workflow() -> List[Dict[str, Any]]:
    """Data transformation automation workflow"""
    try:
        # HTTP Request
        response = requests.get('https://api.example.com/data')
        response.raise_for_status()
        raw_data = response.json()
        
        # Transform Data Node
        transformed_data = [
            {
                'id': item.get('id'),
                'title': item.get('name', 'Untitled').upper(),
                'category': item.get('type', 'general'),
                'processed': True,
                'timestamp': datetime.now().isoformat()
            }
            for item in raw_data
        ]
        
        print(f"Transformed {len(transformed_data)} items")
        return transformed_data
        
    except Exception as e:
        print(f"Workflow failed: {e}")
        raise

if __name__ == "__main__":
    result = workflow()
    print(f"Workflow completed with {len(result)} items")`,

    conditional: `# Generated by Automate2Code ✨
import requests
from typing import Dict, List, Any, Union

def workflow() -> Union[List[List[Dict]], List[Dict]]:
    """Conditional logic automation workflow"""
    try:
        # HTTP Request
        response = requests.get('https://api.example.com/data')
        response.raise_for_status()
        data = response.json()
        
        # Conditional Logic Node
        if len(data) > 10:
            print(f"Processing large dataset: {len(data)} items")
            
            # Handle large dataset - batch processing
            batched = []
            batch_size = 10
            for i in range(0, len(data), batch_size):
                batch = data[i:i + batch_size]
                batched.append(batch)
            
            return batched
            
        else:
            print(f"Processing small dataset: {len(data)} items")
            
            # Handle small dataset - direct processing
            return [
                {**item, 'processed': True}
                for item in data
            ]
            
    except Exception as e:
        print(f"Workflow failed: {e}")
        raise

if __name__ == "__main__":
    result = workflow()
    print(f"Workflow completed: {type(result).__name__}")`,

    output: `# Generated by Automate2Code ✨
import requests
import json
from datetime import datetime
from typing import Dict, Any

def workflow() -> Dict[str, Any]:
    """Output automation workflow with data export"""
    try:
        # HTTP Request
        response = requests.get('https://api.example.com/data')
        response.raise_for_status()
        data = response.json()
        
        # Process data
        processed = [
            {
                **item,
                'processed': True,
                'timestamp': datetime.now().isoformat()
            }
            for item in data
        ]
        
        # Output Node - Export Results
        with open('output.json', 'w', encoding='utf-8') as f:
            json.dump(processed, f, indent=2, ensure_ascii=False)
        
        print(f"Successfully exported {len(processed)} items to output.json")
        
        # Preview first 5 items
        for i, item in enumerate(processed[:5]):
            print(f"Item {i+1}: {item}")
        
        return {
            'success': True,
            'items_processed': len(processed),
            'output_file': 'output.json'
        }
        
    except Exception as e:
        print(f"Workflow failed: {e}")
        raise

if __name__ == "__main__":
    result = workflow()
    print(f"Final result: {result}")`,
  }
};

export const CodePanel = ({ language, nodes }: CodePanelProps) => {
  const [copied, setCopied] = useState(false);
  
  const generatedCode = useMemo(() => {
    if (!nodes || nodes.length === 0) {
      return codeTemplates[language].empty;
    }
    
    const nodeTypes = nodes.map(node => node.data?.nodeType).filter(Boolean);
    
    if (nodeTypes.includes('output')) {
      return codeTemplates[language].output;
    } else if (nodeTypes.includes('conditional')) {
      return codeTemplates[language].conditional;
    } else if (nodeTypes.includes('transform')) {
      return codeTemplates[language].transform;
    } else if (nodeTypes.includes('http')) {
      return codeTemplates[language].http;
    }
    
    return codeTemplates[language].empty;
  }, [language, nodes]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generatedCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div 
      className="h-full flex flex-col"
      initial={{ opacity: 0, x: 50 }}
      animate={{ opacity: 1, x: 0 }}
      transition={{ duration: 0.5 }}
    >
      <div className="p-4 border-b border-border bg-surface-elevated">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <h3 className="font-semibold">Generated Code</h3>
          </div>
          
          <Badge variant="secondary" className="text-xs">
            {language === 'javascript' ? 'JS' : 'PY'}
          </Badge>
        </div>
        
        <div className="flex gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            className="flex-1 hover-lift"
          >
            <AnimatePresence mode="wait">
              {copied ? (
                <motion.div
                  key="check"
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  exit={{ scale: 0 }}
                  className="flex items-center gap-1"
                >
                  <Check className="w-3 h-3 text-success" />
                  <span className="text-xs">Copied!</span>
                </motion.div>
              ) : (
                <motion.div
                  key="copy"
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  exit={{ scale: 0 }}
                  className="flex items-center gap-1"
                >
                  <Copy className="w-3 h-3" />
                  <span className="text-xs">Copy</span>
                </motion.div>
              )}
            </AnimatePresence>
          </Button>
          
          <Button
            variant="outline"
            size="sm"
            className="hover-lift"
          >
            <Download className="w-3 h-3 mr-1" />
            <span className="text-xs">Save</span>
          </Button>
        </div>
      </div>

      <div className="flex-1 bg-code-bg">
        <MonacoEditor
          height="100%"
          language={language}
          value={generatedCode}
          theme="vs-dark"
          options={{
            readOnly: true,
            minimap: { enabled: false },
            fontSize: 13,
            lineNumbers: 'on',
            scrollBeyondLastLine: false,
            automaticLayout: true,
            padding: { top: 16, bottom: 16 },
            fontFamily: 'JetBrains Mono, Consolas, Monaco, monospace',
            lineHeight: 1.6,
            renderLineHighlight: 'none',
            selectionHighlight: false,
            overviewRulerBorder: false,
            hideCursorInOverviewRuler: true,
            scrollbar: {
              vertical: 'auto',
              horizontal: 'auto',
              verticalScrollbarSize: 8,
              horizontalScrollbarSize: 8,
            },
          }}
        />
      </div>

      <div className="p-3 border-t border-border bg-surface-elevated">
        <div className="flex items-center justify-between text-xs text-muted-foreground">
          <span>{nodes.length} nodes connected</span>
          <span>{generatedCode.split('\n').length} lines</span>
        </div>
      </div>
    </motion.div>
  );
};