import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { motion, AnimatePresence } from "framer-motion";
import {
  Settings,
  Code,
  Play,
  User,
  Key,
  Eye,
  EyeOff,
  CheckCircle,
  Clock,
  AlertCircle,
  Copy,
  Download,
} from "lucide-react";
import { Node } from "@xyflow/react";
import MonacoEditor from "@monaco-editor/react";

interface SidebarProps {
  nodes: Node[];
  selectedNode?: Node | null;
}

interface ExecutionStep {
  id: string;
  name: string;
  status: "pending" | "running" | "completed" | "error";
  timestamp?: Date;
  duration?: number;
}

const tabs = [
  { id: "properties", label: "Properties", icon: Settings },
  { id: "execution", label: "Execution", icon: Play },
  { id: "code", label: "Code", icon: Code },
  { id: "settings", label: "Settings", icon: User },
];

export const Sidebar = ({ nodes, selectedNode }: SidebarProps) => {
  const [activeTab, setActiveTab] = useState("code");
  const [executionSteps, setExecutionSteps] = useState<ExecutionStep[]>([
    {
      id: "1",
      name: "Initialize Workflow",
      status: "completed",
      timestamp: new Date(),
      duration: 120,
    },
    { id: "2", name: "HTTP Request", status: "running" },
    { id: "3", name: "Transform Data", status: "pending" },
    { id: "4", name: "Output Result", status: "pending" },
  ]);

  const generateCode = () => {
    if (nodes.length === 0) {
      return `# Welcome to Automate2Code! ✨
# Add nodes to your canvas to see generated code here

async def workflow():
    # Your automation workflow will appear here
    print('Ready to build something amazing!')
    
if __name__ == "__main__":
    workflow()`;
    }

    const httpNodes = nodes.filter((node) => node.data?.nodeType === "http");
    const transformNodes = nodes.filter(
      (node) => node.data?.nodeType === "transform"
    );

    return `# Generated by Automate2Code ✨
import requests
import json
from datetime import datetime

async def workflow():
    try:
${httpNodes
  .map(
    (node, i) => `        # HTTP Request Node ${i + 1}
        response${i + 1} = requests.get(
            'https://api.example.com/data',
            headers={
                'Content-Type': 'application/json',
                'Authorization': 'Bearer YOUR_TOKEN'
            }
        )
        
        data${i + 1} = response${i + 1}.json()
        print(f'Fetched data ${i + 1}: {data${i + 1}}')`
  )
  .join("\n\n")}

${transformNodes
  .map(
    (node, i) => `        # Transform Data Node ${i + 1}
        transformed_data${i + 1} = [
            {**item, 'processed': True, 'timestamp': datetime.now().isoformat()}
            for item in data${i + 1}
        ]`
  )
  .join("\n\n")}
        
        return transformed_data1 if 'transformed_data1' in locals() else data1
    except Exception as error:
        print(f'Workflow failed: {error}')
        raise error

if __name__ == "__main__":
    workflow()`;
  };

  const renderPropertiesTab = () => {
    if (!selectedNode) {
      return (
        <div className="p-6 text-center">
          <div className="rounded-full bg-surface/50 w-16 h-16 flex items-center justify-center mx-auto mb-4">
            <Settings className="w-8 h-8 text-muted-foreground" />
          </div>
          <h3 className="font-medium text-foreground mb-2">No Node Selected</h3>
          <p className="text-sm text-muted-foreground">
            Select a node on the canvas to configure its properties
          </p>
        </div>
      );
    }

    const nodeType = selectedNode.data?.nodeType;

    return (
      <div className="p-6 space-y-6">

        {nodeType === "http" && (
          <div className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="api-endpoint">API Endpoint</Label>
              <Input
                id="api-endpoint"
                type="text"
                placeholder="https://api.example.com/data"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="http-method">HTTP Method</Label>
              <Select>
                <SelectTrigger>
                  <SelectValue placeholder="Select method" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="GET">GET</SelectItem>
                  <SelectItem value="POST">POST</SelectItem>
                  <SelectItem value="PUT">PUT</SelectItem>
                  <SelectItem value="DELETE">DELETE</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="api-key" className="flex items-center gap-2">
                <Key className="w-4 h-4" />
                Authentication
              </Label>
              <div className="relative">
                <Input
                  id="api-key"
                  type="password"
                  placeholder="Enter your API key"
                  className="pr-12"
                />
                <Button
                  variant="ghost"
                  size="sm"
                  className="absolute right-2 top-1/2 -translate-y-1/2 h-8 w-8 p-0 hover:bg-surface"
                >
                  <EyeOff className="w-4 h-4" />
                </Button>
              </div>
            </div>

            <div className="space-y-2">
              <Label htmlFor="headers">Request Headers</Label>
              <Textarea
                id="headers"
                placeholder="Content-Type: application/json&#10;Accept: application/json"
                className="h-24 font-mono text-sm"
              />
            </div>
          </div>
        )}

        {nodeType === "transform" && (
          <div className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="transform-script">Transformation Script</Label>
              <Textarea
                id="transform-script"
                placeholder="data.map(item => ({ ...item, processed: true }))"
                className="h-32 font-mono text-sm"
              />
            </div>
          </div>
        )}

        {nodeType === "conditional" && (
          <div className="space-y-5">
            <div className="space-y-2">
              <Label htmlFor="condition">Condition Expression</Label>
              <Input
                id="condition"
                type="text"
                placeholder="data.length > 0"
                className="font-mono text-sm"
              />
            </div>
          </div>
        )}

        <Button className="w-full py-3 font-medium">Save Configuration</Button>
      </div>
    );
  };

  const renderExecutionTab = () => {
    return (
      <div className="p-6 space-y-6">
        <div className="space-y-3">
          {executionSteps.map((step, index) => (
            <motion.div
              key={step.id}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: index * 0.1 }}
              className="flex items-center gap-4 p-4 rounded-lg border border-border bg-surface/50 hover:bg-surface/80 transition-colors"
            >
              <div className="flex-shrink-0">
                {step.status === "completed" && (
                  <div className="p-1 rounded-full">
                    <CheckCircle className="w-4 h-4 text-green-500" />
                  </div>
                )}
                {step.status === "running" && (
                  <motion.div
                    animate={{ rotate: 360 }}
                    transition={{
                      duration: 2,
                      repeat: Infinity,
                      ease: "linear",
                    }}
                    className="p-1 rounded-full"
                  >
                    <Clock className="w-4 h-4 text-blue-500" />
                  </motion.div>
                )}
                {step.status === "pending" && (
                  <div className="p-1 rounded-full">
                    <Clock className="w-4 h-4 text-muted-foreground" />
                  </div>
                )}
                {step.status === "error" && (
                  <div className="p-1 rounded-full">
                    <AlertCircle className="w-4 h-4 text-red-500" />
                  </div>
                )}
              </div>

              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium truncate text-foreground">
                  {step.name}
                </p>
                {step.timestamp && (
                  <p className="text-xs text-muted-foreground">
                    {step.timestamp.toLocaleTimeString()}
                    {step.duration && ` • ${step.duration}ms`}
                  </p>
                )}
              </div>

              <Badge
                variant={
                  step.status === "completed"
                    ? "default"
                    : step.status === "running"
                    ? "secondary"
                    : step.status === "error"
                    ? "destructive"
                    : "outline"
                }
                className="text-xs font-medium"
              >
                {step.status}
              </Badge>
            </motion.div>
          ))}
        </div>

        <div className="border-t border-border pt-6">
          <h4 className="font-medium mb-3 text-foreground">Execution Log</h4>
          <div className="bg-background border border-border rounded-lg p-4 text-xs font-mono max-h-40 overflow-y-auto space-y-1">
            <div className="text-green-500">[12:34:56] Workflow started</div>
            <div className="text-blue-500">
              [12:34:57] HTTP request initiated
            </div>
            <div className="text-blue-500">
              [12:34:58] Response received (200 OK)
            </div>
            <div className="text-yellow-500">[12:34:59] Processing data...</div>
          </div>
        </div>
      </div>
    );
  };

  const renderCodeTab = () => {
    const code = generateCode();

    return (
      <div className="flex flex-col h-full">
        <div className="p-6 border-b border-border">
          <div className="flex items-center justify-between mb-4">
            <div>
              <p className="mt-1">
                Auto-generated workflow code ready to use
              </p>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="px-3">
                <Copy className="w-4 h-4 mr-2" />
                Copy
              </Button>
              <Button variant="outline" size="sm" className="px-3">
                <Download className="w-4 h-4 mr-2" />
                Export
              </Button>
            </div>
          </div>
          <div className="flex gap-2">
            <Badge variant="outline" className="text-xs">
              {nodes.length} {nodes.length === 1 ? "node" : "nodes"}
            </Badge>
          </div>
        </div>

        <div className="flex-1 bg-background">
          <MonacoEditor
            height="100%"
            language="python"
            value={code}
            theme="vs-dark"
            options={{
              readOnly: true,
              minimap: { enabled: false },
              fontSize: 13,
              lineNumbers: "on",
              wordWrap: "on",
              scrollBeyondLastLine: false,
              automaticLayout: true,
              padding: { top: 16, bottom: 16 },
            }}
          />
        </div>
      </div>
    );
  };

  const renderSettingsTab = () => {
    return (
      <div className="p-6 space-y-6">
        <div className="space-y-5">
          <div className="space-y-2">
            <Label htmlFor="workflow-name">Workflow Name</Label>
            <Input
              id="workflow-name"
              type="text"
              placeholder="My Automation Workflow"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="description">Description</Label>
            <Textarea
              id="description"
              placeholder="Describe what this workflow does..."
              className="h-24"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="environment">Environment</Label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="Select environment" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="development">Development</SelectItem>
                <SelectItem value="staging">Staging</SelectItem>
                <SelectItem value="production">Production</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-3">
            <Label>Error Handling</Label>
            <div className="space-y-3">
              <div className="flex items-center space-x-2">
                <Checkbox id="stop-on-error" defaultChecked />
                <Label htmlFor="stop-on-error" className="text-sm font-normal">
                  Stop on first error
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox id="retry-failed" />
                <Label htmlFor="retry-failed" className="text-sm font-normal">
                  Retry failed nodes
                </Label>
              </div>
              <div className="flex items-center space-x-2">
                <Checkbox id="detailed-logging" defaultChecked />
                <Label
                  htmlFor="detailed-logging"
                  className="text-sm font-normal"
                >
                  Enable detailed logging
                </Label>
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="timeout">Timeout (seconds)</Label>
            <Input id="timeout" type="number" placeholder="30" />
          </div>
        </div>

        <div className="space-y-3 pt-6 border-t border-border">
          <Button className="w-full py-3 font-medium">Save Settings</Button>
          <Button variant="outline" className="w-full py-3">
            Export Workflow
          </Button>
        </div>
      </div>
    );
  };

  const renderTabContent = () => {
    switch (activeTab) {
      case "properties":
        return renderPropertiesTab();
      case "execution":
        return renderExecutionTab();
      case "code":
        return renderCodeTab();
      case "settings":
        return renderSettingsTab();
      default:
        return renderCodeTab();
    }
  };

  return (
    <div className="w-full h-full flex flex-col bg-surface border-l border-border">
      {/* Tab Navigation */}
      <div className="p-4">
        <div className="relative bg-surface border border-border rounded-full p-1">
          <div className="grid grid-cols-4 relative">
            {/* Moving background */}
            <motion.div
              className="absolute inset-y-1 bg-primary rounded-full"
              initial={false}
              animate={{
                x: `${tabs.findIndex(tab => tab.id === activeTab) * 100}%`,
              }}
              transition={{
                type: "spring",
                stiffness: 300,
                damping: 30,
              }}
              style={{ width: "calc(25% - 4px)", margin: "0 2px" }}
            />
            
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex gap-3 items-center justify-center cursor-pointer px-3 py-3 text-xs font-medium transition-all relative z-10 rounded-full ${
                    activeTab === tab.id
                      ? "text-primary-foreground"
                      : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  <Icon className="w-4 h-4 text-white stroke-2 " />
                  <span className="hidden sm:inline text-white">{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Tab Content */}
      <div className="flex-1 overflow-hidden">
        <AnimatePresence mode="wait">
          <motion.div
            key={activeTab}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="h-full overflow-y-auto"
          >
            {renderTabContent()}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
};
