import React from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Copy, Download } from "lucide-react";
import { Node } from "@xyflow/react";
import MonacoEditor from "@monaco-editor/react";

interface CodeTabProps {
  nodes: Node[];
}

const generateCode = (nodes: Node[]) => {
  if (nodes.length === 0) {
    return `# Welcome to Automate2Code! ✨
# Add nodes to your canvas to see generated code here

async def workflow():
    # Your automation workflow will appear here
    print('Ready to build something amazing!')
    
if __name__ == "__main__":
    workflow()`;
  }

  const httpNodes = nodes.filter((node) => node.data?.nodeType === "http");
  const transformNodes = nodes.filter(
    (node) => node.data?.nodeType === "transform"
  );

  return `# Generated by Automate2Code ✨
import requests
import json
from datetime import datetime

async def workflow():
    try:
${httpNodes
  .map(
    (node, i) => `        # HTTP Request Node ${i + 1}
        response${i + 1} = requests.get(
            'https://api.example.com/data',
            headers={
                'Content-Type': 'application/json',
                'Authorization': 'Bearer YOUR_TOKEN'
            }
        )
        
        data${i + 1} = response${i + 1}.json()
        print(f'Fetched data ${i + 1}: {data${i + 1}}')`
  )
  .join("\n\n")}

${transformNodes
  .map(
    (node, i) => `        # Transform Data Node ${i + 1}
        transformed_data${i + 1} = [
            {**item, 'processed': True, 'timestamp': datetime.now().isoformat()}
            for item in data${i + 1}
        ]`
  )
  .join("\n\n")}
        
        return transformed_data1 if 'transformed_data1' in locals() else data1
    except Exception as error:
        print(f'Workflow failed: {error}')
        raise error

if __name__ == "__main__":
    workflow()`;
};

export const CodeTab = ({ nodes }: CodeTabProps) => {
  const code = generateCode(nodes);

  return (
    <div className="flex flex-col h-full">
      <div className="p-6 border-b border-border">
        <div className="flex items-center justify-between mb-4">
          <div>
            <p className="mt-1">
              Auto-generated workflow code ready to use
            </p>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" className="px-3">
              <Copy className="w-4 h-4 mr-2" />
              Copy
            </Button>
            <Button variant="outline" size="sm" className="px-3">
              <Download className="w-4 h-4 mr-2" />
              Export
            </Button>
          </div>
        </div>
        <div className="flex gap-2">
          <Badge variant="outline" className="text-xs">
            {nodes.length} {nodes.length === 1 ? "node" : "nodes"}
          </Badge>
        </div>
      </div>

      <div className="flex-1 bg-background">
        <MonacoEditor
          height="100%"
          language="python"
          value={code}
          theme="vs-dark"
          options={{
            readOnly: true,
            minimap: { enabled: false },
            fontSize: 13,
            lineNumbers: "on",
            wordWrap: "on",
            scrollBeyondLastLine: false,
            automaticLayout: true,
            padding: { top: 16, bottom: 16 },
          }}
        />
      </div>
    </div>
  );
};
